import { LiveWebcam } from '../types';

export const USER_LIVE_WEBCAMS: LiveWebcam[] = [
  // --- NORTH AMERICA ---
  {
    id: 'yt-JQ_jwk_7OVE',
    callsign: 'OS-NYC-01',
    sector: 'SEC-01 (NORTH AMERICA EAST)',
    elevation: '45m ASL',
    sensorType: 'Optical 4K Ultra PTZ',
    title: 'EarthCam Live: Times Square North 4K (Broadway)',
    channelName: 'EarthCam',
    city: 'New York City',
    stateOrRegion: 'New York',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 40.7589,
    longitude: -73.9851,
    category: 'Street & Traffic',
    youtubeId: 'JQ_jwk_7OVE',
    embedUrl: 'https://www.youtube-nocookie.com/embed/JQ_jwk_7OVE?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '4K Ultra HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 9400,
    status: 'Online 24/7',
    description: 'Official 4K Ultra HD live camera feed by EarthCam positioned at Times Square North, overlooking Broadway, glowing digital billboards, yellow taxis, and Manhattan pedestrians.',
    tags: ['EarthCam', 'Times Square', 'New York', 'Broadway', 'Manhattan 4K'],
  },
  {
    id: 'yt-EO_1LWqsCNE',
    callsign: 'OS-LAX-02',
    sector: 'SEC-01 (NORTH AMERICA WEST)',
    elevation: '18m ASL',
    sensorType: 'Coastal Wide Optical Array',
    title: 'Los Angeles Live Cam: Venice Beach & Boardwalk (Venice V Hotel)',
    channelName: 'Teleport.camera',
    city: 'Los Angeles',
    stateOrRegion: 'California',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 33.9870,
    longitude: -118.4735,
    category: 'Beach & Ocean',
    youtubeId: 'EO_1LWqsCNE',
    embedUrl: 'https://www.youtube-nocookie.com/embed/EO_1LWqsCNE?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Los_Angeles (PDT)',
    timezoneOffsetHours: -7,
    viewersCount: 4200,
    status: 'Online 24/7',
    description: 'Direct live stream from the rooftop of Venice V Hotel overlooking the famous Venice Beach Boardwalk, palm tree promenades, skate park, and the Pacific Ocean surf.',
    tags: ['Venice Beach', 'Los Angeles', 'California', 'Pacific Ocean', 'Boardwalk'],
  },
  {
    id: 'yt-OUBslrCqREs',
    callsign: 'OS-LGA-03',
    sector: 'SEC-01 (NORTH AMERICA EAST)',
    elevation: '6m ASL',
    sensorType: 'Avionics Long-Range Radar Optical',
    title: 'LaGuardia Airport (LGA) Live 24/7 Runway Operations',
    channelName: 'Flightradar24',
    city: 'New York City',
    stateOrRegion: 'New York',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 40.7769,
    longitude: -73.8740,
    category: 'Airport & Aviation',
    youtubeId: 'OUBslrCqREs',
    embedUrl: 'https://www.youtube-nocookie.com/embed/OUBslrCqREs?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 5100,
    status: 'Online 24/7',
    description: 'Flightradar24 official live aviation broadcast tracking aircraft approaches, landings, takeoffs, and tarmac ground movements at LaGuardia Airport (LGA) in Queens, NY.',
    tags: ['Flightradar24', 'LGA Airport', 'Aviation', 'New York', 'Planespotting'],
  },
  {
    id: 'yt-zP6QyJAXa4c',
    callsign: 'OS-SAN-04',
    sector: 'SEC-01 (NORTH AMERICA WEST)',
    elevation: '5m ASL',
    sensorType: 'Air-Traffic Telephoto Optical Node',
    title: 'San Diego International Airport (SAN) Live Plane Spotting Action',
    channelName: 'AIRLINE VIDEOS',
    city: 'San Diego',
    stateOrRegion: 'California',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 32.7338,
    longitude: -117.1933,
    category: 'Airport & Aviation',
    youtubeId: 'zP6QyJAXa4c',
    embedUrl: 'https://www.youtube-nocookie.com/embed/zP6QyJAXa4c?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Los_Angeles (PDT)',
    timezoneOffsetHours: -7,
    viewersCount: 6800,
    status: 'Live Stream',
    description: 'High-definition live aviation broadcast by AIRLINE VIDEOS covering aircraft landing approaches over downtown San Diego skyline directly onto Runway 27.',
    tags: ['AIRLINE VIDEOS', 'San Diego', 'SAN Airport', 'Aviation', 'California'],
  },
  {
    id: 'yt-AiNCbGzabVo',
    callsign: 'OS-BOS-05',
    sector: 'SEC-01 (NORTH AMERICA EAST)',
    elevation: '22m ASL',
    sensorType: 'Multi-Stream Satellite Hub',
    title: 'Live Cameras Around the World: Music, Timelapse & Travel',
    channelName: 'Boston and Maine Live',
    city: 'Boston',
    stateOrRegion: 'Massachusetts',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 42.3601,
    longitude: -71.0589,
    category: 'Global Network',
    youtubeId: 'AiNCbGzabVo',
    embedUrl: 'https://www.youtube-nocookie.com/embed/AiNCbGzabVo?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 2300,
    status: 'Online 24/7',
    description: 'Continuous curated multi-webcam stream featuring international landscapes, rail corridors, harbor vistas, and ambient travel timelapses.',
    tags: ['Boston and Maine', 'World Webcams', 'Timelapse', 'Ambient', 'Travel'],
  },
  {
    id: 'yt-MW3fisTCXRQ',
    callsign: 'OS-ORL-20',
    sector: 'SEC-01 (NORTH AMERICA EAST)',
    elevation: '30m ASL',
    sensorType: 'Ultra HD World Network',
    title: 'World Live Webcam 24/7 – Global Cityscapes & Sky Cams',
    channelName: 'Earth World Views',
    city: 'Miami & Orlando',
    stateOrRegion: 'Florida',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 25.7617,
    longitude: -80.1918,
    category: 'Global Network',
    youtubeId: 'MW3fisTCXRQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/MW3fisTCXRQ?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 8100,
    status: 'Online 24/7',
    description: 'Continuous 24/7 global webcam network stream broadcasting cityscapes, active harbors, beach resorts, and skyline sunsets worldwide.',
    tags: ['World Webcams', 'Cityscapes', 'Skyline', 'Florida', 'EarthCam'],
  },
  {
    id: 'yt-0FBiyFpV__g',
    callsign: 'OS-CHI-21',
    sector: 'SEC-01 (NORTH AMERICA CENTRAL)',
    elevation: '180m ASL',
    sensorType: 'Metropolitan High-Rise Lens',
    title: 'All Live Webcams: High Definition World Views 24/7',
    channelName: 'Global Live Feeds',
    city: 'Chicago',
    stateOrRegion: 'Illinois',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 41.8781,
    longitude: -87.6298,
    category: 'Global Network',
    youtubeId: '0FBiyFpV__g',
    embedUrl: 'https://www.youtube-nocookie.com/embed/0FBiyFpV__g?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Chicago (CDT)',
    timezoneOffsetHours: -5,
    viewersCount: 6500,
    status: 'Online 24/7',
    description: 'High definition continuous 24/7 stream tracking urban centers, traffic grids, and international landmark perspectives.',
    tags: ['Chicago', 'All Live Webcams', 'Urban Center', 'Traffic Grid', 'USA'],
  },
  {
    id: 'yt-F0GOOP82094',
    callsign: 'OS-SEA-22',
    sector: 'SEC-01 (NORTH AMERICA WEST)',
    elevation: '45m ASL',
    sensorType: 'Pacific Northwest Harbor Array',
    title: 'Earth Live Network: Real-Time World Ports & Skies',
    channelName: 'Earth Live Feeds',
    city: 'Seattle',
    stateOrRegion: 'Washington',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 47.6062,
    longitude: -122.3321,
    category: 'Global Network',
    youtubeId: 'F0GOOP82094',
    embedUrl: 'https://www.youtube-nocookie.com/embed/F0GOOP82094?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Los_Angeles (PDT)',
    timezoneOffsetHours: -7,
    viewersCount: 5200,
    status: 'Online 24/7',
    description: 'Real-time multi-angle live stream covering major deep-water ports, sound channels, and mountainous horizon overlooks.',
    tags: ['Seattle', 'Pacific Northwest', 'Harbor Cam', 'World Stream', 'Live 24/7'],
  },
  {
    id: 'yt-sKcmQQqzQcM',
    callsign: 'OS-HNL-23',
    sector: 'SEC-01 (PACIFIC ISLANDS)',
    elevation: '8m ASL',
    sensorType: 'Tropical Coastal Optical Array',
    title: 'All Live Webcams: Pacific Horizons & Ocean Coastlines',
    channelName: 'Ocean View Live',
    city: 'Honolulu',
    stateOrRegion: 'Hawaii',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 21.3069,
    longitude: -157.8583,
    category: 'Beach & Ocean',
    youtubeId: 'sKcmQQqzQcM',
    embedUrl: 'https://www.youtube-nocookie.com/embed/sKcmQQqzQcM?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Pacific/Honolulu (HST)',
    timezoneOffsetHours: -10,
    viewersCount: 4100,
    status: 'Online 24/7',
    description: 'Pacific oceanfront live camera capturing tropical tides, beach promenades, volcanic horizons, and surf breaks.',
    tags: ['Hawaii', 'Honolulu', 'Pacific', 'Beach Cam', 'Ocean Live'],
  },
  {
    id: 'yt-CmtuOVxcKRo',
    callsign: 'OS-SFO-24',
    sector: 'SEC-01 (NORTH AMERICA WEST)',
    elevation: '67m ASL',
    sensorType: 'Bay Area Optical Matrix',
    title: 'San Francisco Bay & Golden Gate Live Surveillance',
    channelName: 'Bay Area Webcams',
    city: 'San Francisco',
    stateOrRegion: 'California',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 37.8199,
    longitude: -122.4783,
    category: 'Landmark',
    youtubeId: 'CmtuOVxcKRo',
    embedUrl: 'https://www.youtube-nocookie.com/embed/CmtuOVxcKRo?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Los_Angeles (PDT)',
    timezoneOffsetHours: -7,
    viewersCount: 7300,
    status: 'Online 24/7',
    description: 'Live continuous feed monitoring San Francisco Bay, maritime traffic under Golden Gate Bridge, and coastal fog developments.',
    tags: ['San Francisco', 'Golden Gate', 'Bay Area', 'Maritime', 'California'],
  },
  {
    id: 'yt-EFum1rGUdkk',
    callsign: 'OS-TOK-25',
    sector: 'SEC-04 (EAST ASIA)',
    elevation: '120m ASL',
    sensorType: 'Ultra 4K Metropole Cam',
    title: 'Tokyo Shibuya Crossing & Shinjuku Live Stream 4K',
    channelName: 'Tokyo Live Cam',
    city: 'Tokyo',
    stateOrRegion: 'Kanto',
    country: 'Japan',
    countryCode: 'JP',
    continent: 'Asia',
    latitude: 35.6595,
    longitude: 139.7004,
    category: 'Street & Traffic',
    youtubeId: 'EFum1rGUdkk',
    embedUrl: 'https://www.youtube-nocookie.com/embed/EFum1rGUdkk?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '4K Ultra HD',
    fps: 60,
    timezone: 'Asia/Tokyo (JST)',
    timezoneOffsetHours: 9,
    viewersCount: 14200,
    status: 'Online 24/7',
    description: 'Live 4K Ultra HD surveillance overlooking Shibuya Scramble crossing and Tokyo downtown metropolis neon lights and foot traffic.',
    tags: ['Tokyo', 'Shibuya', 'Japan', 'Neon Lights', '4K Metropolis'],
  },
  {
    id: 'yt-ZvYvZLfPatQ',
    callsign: 'OS-SYD-26',
    sector: 'SEC-04 (OCEANIA)',
    elevation: '40m ASL',
    sensorType: 'Coastal 4K PTZ Array',
    title: 'Sydney Bondi Beach & Coastal Surf Live Cam',
    channelName: 'Australia Live',
    city: 'Sydney',
    stateOrRegion: 'New South Wales',
    country: 'Australia',
    countryCode: 'AU',
    continent: 'Oceania',
    latitude: -33.8915,
    longitude: 151.2767,
    category: 'Beach & Ocean',
    youtubeId: 'ZvYvZLfPatQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ZvYvZLfPatQ?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Australia/Sydney (AEST)',
    timezoneOffsetHours: 10,
    viewersCount: 5600,
    status: 'Online 24/7',
    description: 'World-famous Bondi Beach live ocean surveillance stream showing surf swells, ocean baths, and golden sands.',
    tags: ['Bondi Beach', 'Sydney', 'Australia', 'Surf Cam', 'Ocean Live'],
  },
  {
    id: 'yt-WKGK_hYnlGE',
    callsign: 'OS-DXB-27',
    sector: 'SEC-04 (MIDDLE EAST)',
    elevation: '350m ASL',
    sensorType: 'High-Altitude Tower Array',
    title: 'Dubai Marina & Downtown Burj Khalifa Skyline Live 2026',
    channelName: 'Emirates Live Vision',
    city: 'Dubai',
    stateOrRegion: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    continent: 'Asia',
    latitude: 25.0805,
    longitude: 55.1403,
    category: 'Landmark',
    youtubeId: 'WKGK_hYnlGE',
    embedUrl: 'https://www.youtube-nocookie.com/embed/WKGK_hYnlGE?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '4K Ultra HD',
    fps: 60,
    timezone: 'Asia/Dubai (GST)',
    timezoneOffsetHours: 4,
    viewersCount: 11200,
    status: 'Online 24/7',
    description: 'Spectacular panoramic high-resolution live camera streaming Dubai Marina skyscrapers, yachts, and the Arabian Gulf.',
    tags: ['Dubai', 'Burj Khalifa', 'Marina', 'UAE', 'Skyscraper Live'],
  },
  {
    id: 'yt-rvtygG4n6ew',
    callsign: 'OS-PAR-28',
    sector: 'SEC-02 (EUROPE WEST)',
    elevation: '70m ASL',
    sensorType: 'Historic Landmark Optical Node',
    title: 'Paris Eiffel Tower & Seine River Live Panorama 2026',
    channelName: 'France Live Stream',
    city: 'Paris',
    stateOrRegion: 'Île-de-France',
    country: 'France',
    countryCode: 'FR',
    continent: 'Europe',
    latitude: 48.8584,
    longitude: 2.2945,
    category: 'Landmark',
    youtubeId: 'rvtygG4n6ew',
    embedUrl: 'https://www.youtube-nocookie.com/embed/rvtygG4n6ew?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/Paris (CEST)',
    timezoneOffsetHours: 2,
    viewersCount: 9800,
    status: 'Online 24/7',
    description: 'Iconic live view of the Eiffel Tower, Champ de Mars, and tourist riverboat cruises gliding along the River Seine in Paris.',
    tags: ['Paris', 'Eiffel Tower', 'France', 'Seine River', 'Landmark Live'],
  },

  // --- INDIA LIVE WEBCAMS ---
  {
    id: 'yt-7wBNtsgqNOI',
    callsign: 'OS-DEL-06',
    sector: 'SEC-04 (INDIA NORTH)',
    elevation: '216m ASL',
    sensorType: 'Urban Density High-Res Sensor',
    title: 'India: New Delhi Chandni Chowk & Old Delhi Heritage Stream',
    channelName: 'LADmob',
    city: 'New Delhi',
    stateOrRegion: 'Delhi NCR',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 28.6506,
    longitude: 77.2303,
    category: 'Street & Traffic',
    youtubeId: '7wBNtsgqNOI',
    embedUrl: 'https://www.youtube-nocookie.com/embed/7wBNtsgqNOI?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '4K Ultra HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 7800,
    status: 'Online 24/7',
    description: 'High-definition broadcast capturing the vibrant atmosphere, bustling heritage markets, rickshaws, and iconic street life of Chandni Chowk and Old Delhi.',
    tags: ['Delhi', 'Chandni Chowk', 'Old Delhi', 'India Street Life', 'Heritage 4K'],
  },
  {
    id: 'yt-Bx24NlFh3GQ',
    callsign: 'OS-MUM-30',
    sector: 'SEC-04 (INDIA WEST)',
    elevation: '14m ASL',
    sensorType: 'Metropolitan High-Res CCTV Node',
    title: 'India Live: Mumbai Marine Drive & Arabian Sea Coastline',
    channelName: 'Mumbai Live Watch',
    city: 'Mumbai',
    stateOrRegion: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 18.9438,
    longitude: 72.8232,
    category: 'Beach & Ocean',
    youtubeId: 'Bx24NlFh3GQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/Bx24NlFh3GQ?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 8900,
    status: 'Online 24/7',
    description: 'Continuous live CCTV broadcast streaming the iconic Queens Necklace promenade, Marine Drive coastal traffic, and sunset views over the Arabian Sea.',
    tags: ['Mumbai', 'Marine Drive', 'Queens Necklace', 'Maharashtra', 'India Live'],
  },
  {
    id: 'yt-AkqGOcpDvZU',
    callsign: 'OS-VAR-31',
    sector: 'SEC-04 (INDIA NORTH)',
    elevation: '76m ASL',
    sensorType: 'Spiritual Heritage Optical Sensor',
    title: 'India Live: Varanasi Ganga Ghat & Dashashwamedh Aarti',
    channelName: 'Holy Ganga Live',
    city: 'Varanasi',
    stateOrRegion: 'Uttar Pradesh',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 25.3176,
    longitude: 83.0118,
    category: 'Landmark',
    youtubeId: 'AkqGOcpDvZU',
    embedUrl: 'https://www.youtube-nocookie.com/embed/AkqGOcpDvZU?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 16500,
    status: 'Online 24/7',
    description: '24/7 holy livestream of the sacred Ganges river ghats at Varanasi, featuring historic temple architecture, sunrise boat traffic, and evening Ganga Aarti rituals.',
    tags: ['Varanasi', 'Ganga Ghat', 'Kashi', 'Aarti', 'India Spiritual'],
  },
  {
    id: 'yt-VR-x3HdhKLQ',
    callsign: 'OS-JAI-32',
    sector: 'SEC-04 (INDIA NORTH)',
    elevation: '431m ASL',
    sensorType: 'Heritage Palace Optical Node',
    title: 'India Live: Jaipur Pink City & Hawa Mahal Heritage Cam',
    channelName: 'Rajasthan Heritage Live',
    city: 'Jaipur',
    stateOrRegion: 'Rajasthan',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 26.9239,
    longitude: 75.8267,
    category: 'Landmark',
    youtubeId: 'VR-x3HdhKLQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/VR-x3HdhKLQ?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 6200,
    status: 'Online 24/7',
    description: 'Live scenic broadcast overlooking the Pink City bazaars, royal sandstone palaces, and lively traditional streets of Jaipur, Rajasthan.',
    tags: ['Jaipur', 'Pink City', 'Hawa Mahal', 'Rajasthan', 'India Heritage'],
  },
  {
    id: 'yt-A9NjjAgyj6w',
    callsign: 'OS-GOA-33',
    sector: 'SEC-04 (INDIA WEST)',
    elevation: '6m ASL',
    sensorType: 'Coastal Arabian Sea Array',
    title: 'India Live: Goa Calangute & Baga Beach Ocean Live Cam',
    channelName: 'Goa Waves Live',
    city: 'Goa',
    stateOrRegion: 'Goa',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 15.5439,
    longitude: 73.7554,
    category: 'Beach & Ocean',
    youtubeId: 'A9NjjAgyj6w',
    embedUrl: 'https://www.youtube-nocookie.com/embed/A9NjjAgyj6w?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 7100,
    status: 'Online 24/7',
    description: 'Continuous beachfront livestream showing Goa turquoise waters, shacks, palm-fringed coastlines, and beach sports on Calangute & Baga shores.',
    tags: ['Goa', 'Baga Beach', 'Calangute', 'Arabian Sea', 'India Coastal'],
  },
  {
    id: 'yt-0Kaji9GHl68',
    callsign: 'OS-BLR-34',
    sector: 'SEC-04 (INDIA SOUTH)',
    elevation: '920m ASL',
    sensorType: 'Tech Hub Surveillance Node',
    title: 'India Live: Bengaluru MG Road & Tech Corridor Traffic Stream',
    channelName: 'Bengaluru Tech Live',
    city: 'Bengaluru',
    stateOrRegion: 'Karnataka',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 12.9716,
    longitude: 77.5946,
    category: 'Street & Traffic',
    youtubeId: '0Kaji9GHl68',
    embedUrl: 'https://www.youtube-nocookie.com/embed/0Kaji9GHl68?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 5400,
    status: 'Online 24/7',
    description: 'Real-time traffic surveillance and metropolis operations stream across MG Road, Namma Metro lines, and Bengaluru central business district.',
    tags: ['Bengaluru', 'Bangalore', 'MG Road', 'Tech City', 'Karnataka'],
  },
  {
    id: 'yt-tAWFO8_O_7M',
    callsign: 'OS-CCU-35',
    sector: 'SEC-04 (INDIA EAST)',
    elevation: '9m ASL',
    sensorType: 'Maritime River Optical Array',
    title: 'India Live: Kolkata Howrah Bridge & Hooghly River Cam',
    channelName: 'Kolkata City Live',
    city: 'Kolkata',
    stateOrRegion: 'West Bengal',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 22.5851,
    longitude: 88.3468,
    category: 'Landmark',
    youtubeId: 'tAWFO8_O_7M',
    embedUrl: 'https://www.youtube-nocookie.com/embed/tAWFO8_O_7M?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 6800,
    status: 'Online 24/7',
    description: 'High-definition live video feed framing the world-famous cantilever Howrah Bridge and ferries crossing the sacred Hooghly River in Kolkata.',
    tags: ['Kolkata', 'Howrah Bridge', 'Hooghly River', 'West Bengal', 'India Live'],
  },
  {
    id: 'yt-UNbOvsRAx9U',
    callsign: 'OS-MAA-36',
    sector: 'SEC-04 (INDIA SOUTH)',
    elevation: '7m ASL',
    sensorType: 'Bay of Bengal Maritime Array',
    title: 'India Live: Chennai Marina Beach Promenade & Lighthouse',
    channelName: 'Chennai Coastal Watch',
    city: 'Chennai',
    stateOrRegion: 'Tamil Nadu',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 13.0500,
    longitude: 80.2824,
    category: 'Beach & Ocean',
    youtubeId: 'UNbOvsRAx9U',
    embedUrl: 'https://www.youtube-nocookie.com/embed/UNbOvsRAx9U?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 5900,
    status: 'Online 24/7',
    description: 'Live broadcast capturing one of the worlds longest natural urban beaches along the Bay of Bengal coastline in Chennai, Tamil Nadu.',
    tags: ['Chennai', 'Marina Beach', 'Bay of Bengal', 'Tamil Nadu', 'India Coastal'],
  },
  {
    id: 'yt-FHyFGlVNBOw',
    callsign: 'OS-HAR-37',
    sector: 'SEC-04 (INDIA NORTH)',
    elevation: '314m ASL',
    sensorType: 'Himalayan Foothill Optical Node',
    title: 'India Live: Haridwar Har Ki Pauri Holy Ghats Live Stream',
    channelName: 'Devbhoomi Live Feeds',
    city: 'Haridwar',
    stateOrRegion: 'Uttarakhand',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 29.9564,
    longitude: 78.1706,
    category: 'Landmark',
    youtubeId: 'FHyFGlVNBOw',
    embedUrl: 'https://www.youtube-nocookie.com/embed/FHyFGlVNBOw?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 13400,
    status: 'Online 24/7',
    description: 'Direct 24/7 stream of Har Ki Pauri at Haridwar in the Himalayan foothills where holy devotees take sacred Ganga snan and celebrate Maha Aarti.',
    tags: ['Haridwar', 'Har Ki Pauri', 'Uttarakhand', 'Ganga', 'India Sacred'],
  },
  {
    id: 'yt-u8CbGedbI08',
    callsign: 'OS-BOM-38',
    sector: 'SEC-04 (INDIA WEST)',
    elevation: '25m ASL',
    sensorType: 'Urban Harbour PTZ Array',
    title: 'India Live: Gateway of India & Taj Mahal Palace Mumbai',
    channelName: 'Mumbai Heritage Live',
    city: 'Mumbai',
    stateOrRegion: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 18.9220,
    longitude: 72.8347,
    category: 'Landmark',
    youtubeId: 'u8CbGedbI08',
    embedUrl: 'https://www.youtube-nocookie.com/embed/u8CbGedbI08?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 8700,
    status: 'Online 24/7',
    description: 'Surveillance video feed framing the world-renowned Gateway of India monument and the iconic heritage Taj Mahal Palace Hotel in South Mumbai.',
    tags: ['Gateway of India', 'Taj Hotel', 'South Mumbai', 'Colaba', 'India Live'],
  },
  {
    id: 'yt-cWRSJ3EGuuo',
    callsign: 'OS-HYD-39',
    sector: 'SEC-04 (INDIA CENTRAL)',
    elevation: '542m ASL',
    sensorType: 'Heritage Monument Sensor Node',
    title: 'India Live: Hyderabad Charminar & Historic Old City Bazaar',
    channelName: 'Deccan Live Watch',
    city: 'Hyderabad',
    stateOrRegion: 'Telangana',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 17.3616,
    longitude: 78.4747,
    category: 'Landmark',
    youtubeId: 'cWRSJ3EGuuo',
    embedUrl: 'https://www.youtube-nocookie.com/embed/cWRSJ3EGuuo?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 7600,
    status: 'Online 24/7',
    description: 'Continuous stream of the iconic 16th-century Charminar four-minaret monument and the bustling night pearl bazaars in old city Hyderabad.',
    tags: ['Hyderabad', 'Charminar', 'Telangana', 'Old City', 'India Heritage'],
  },
  {
    id: 'yt--Xlzej8RTTU',
    callsign: 'OS-PUN-40',
    sector: 'SEC-04 (INDIA WEST)',
    elevation: '560m ASL',
    sensorType: 'City Junction Optical Matrix',
    title: 'India Live: Pune Shaniwar Wada & Deccan City Center',
    channelName: 'Pune Live Vision',
    city: 'Pune',
    stateOrRegion: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    continent: 'Asia',
    latitude: 18.5196,
    longitude: 73.8553,
    category: 'Street & Traffic',
    youtubeId: '-Xlzej8RTTU',
    embedUrl: 'https://www.youtube-nocookie.com/embed/-Xlzej8RTTU?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Kolkata (IST)',
    timezoneOffsetHours: 5.5,
    viewersCount: 4900,
    status: 'Online 24/7',
    description: 'Real-time city surveillance observing historic Maratha fortresses, central squares, and urban cultural districts in Pune, Maharashtra.',
    tags: ['Pune', 'Shaniwar Wada', 'Maharashtra', 'Deccan', 'India Live'],
  },

  // --- CYBER / DARKNET / HACKER & CCTV SURVEILLANCE ---
  {
    id: 'yt-qAQX8nQcpEc',
    callsign: 'OS-HCK-41',
    sector: 'SEC-05 (CYBER WARFARE)',
    elevation: 'Deep Underground Bunker',
    sensorType: 'DefCon Threat Intercept Probe',
    title: 'Live Hacker Threat Matrix & Global Cyber Security Stream',
    channelName: 'Cyber Attack Intel',
    city: 'Global Cyber Grid',
    stateOrRegion: 'Cyber Operations',
    country: 'Cyber Operations',
    countryCode: 'CY',
    continent: 'Cyber Ops',
    latitude: 51.5074,
    longitude: -0.1278,
    category: 'Cyber Security / DarkWeb',
    youtubeId: 'qAQX8nQcpEc',
    embedUrl: 'https://www.youtube-nocookie.com/embed/qAQX8nQcpEc?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 12400,
    status: 'Online 24/7',
    description: 'Active cybersecurity radar analyzing DDOS attacks, zero-day threat vectors, satellite command intercepts, and honeypot packet streams.',
    tags: ['Hacker', 'CyberSecurity', 'ThreatIntel', 'DarkNet', 'Live Matrix'],
  },
  {
    id: 'yt-pmE7BE5ASTI',
    callsign: 'OS-HCK-42',
    sector: 'SEC-05 (CYBER WARFARE)',
    elevation: 'Data Vault Level 5',
    sensorType: 'Quantum Cryptanalysis Node',
    title: 'Global Hacker SOC Terminal: Real-Time Cyber Warfare Grid',
    channelName: 'Dark Ops Radar',
    city: 'Geneva Cyber Hub',
    stateOrRegion: 'Cyber Operations',
    country: 'Cyber Operations',
    countryCode: 'CY',
    continent: 'Cyber Ops',
    latitude: 46.2044,
    longitude: 6.1432,
    category: 'Cyber Security / DarkWeb',
    youtubeId: 'pmE7BE5ASTI',
    embedUrl: 'https://www.youtube-nocookie.com/embed/pmE7BE5ASTI?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 9800,
    status: 'Online 24/7',
    description: 'Live terminal stream tracing deep web intrusions, autonomous exploit scans, firewall counters, and encrypted node pings.',
    tags: ['DarkOps', 'Hacker Live', 'CyberGrid', 'SOC Terminal', 'Exploit Monitor'],
  },
  {
    id: 'yt-Y4eIXH7O1z8',
    callsign: 'OS-DRK-43',
    sector: 'SEC-05 (DARKNET NETWORK)',
    elevation: 'Tor Node Node-9',
    sensorType: 'Onion Router Packet Sniffer',
    title: 'DarkNet Live Surveillance & Deep Web Protocol Monitor',
    channelName: 'Deep Web Terminal',
    city: 'Reykjavik Secure Node',
    stateOrRegion: 'DarkNet Sector',
    country: 'Cyber Operations',
    countryCode: 'CY',
    continent: 'Cyber Ops',
    latitude: 64.1466,
    longitude: -21.9426,
    category: 'Cyber Security / DarkWeb',
    youtubeId: 'Y4eIXH7O1z8',
    embedUrl: 'https://www.youtube-nocookie.com/embed/Y4eIXH7O1z8?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 11100,
    status: 'Online 24/7',
    description: 'Darknet network traffic surveillance feed capturing onion routing relays, hidden service telemetry, and cryptographic handshake analysis.',
    tags: ['DarkNet', 'DeepWeb', 'Tor', 'Onion', 'Protocol Analysis'],
  },
  {
    id: 'yt-16MZ49PN0SI',
    callsign: 'OS-DRK-44',
    sector: 'SEC-05 (DARKNET NETWORK)',
    elevation: 'Encrypted Bastion',
    sensorType: 'Tor Hidden Service Probe',
    title: 'DarkWeb Live Webcam: Deep Internet Security Operations',
    channelName: 'Cyber Shield Ops',
    city: 'Amsterdam Cyber Fort',
    stateOrRegion: 'DarkNet Sector',
    country: 'Cyber Operations',
    countryCode: 'CY',
    continent: 'Cyber Ops',
    latitude: 52.3676,
    longitude: 4.9041,
    category: 'Cyber Security / DarkWeb',
    youtubeId: '16MZ49PN0SI',
    embedUrl: 'https://www.youtube-nocookie.com/embed/16MZ49PN0SI?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 8400,
    status: 'Online 24/7',
    description: 'Live investigative telemetry feed monitoring dark web forum anomalies, botnet command nodes, and cyber defense protocols.',
    tags: ['DarkWeb', 'CyberShield', 'Tor Network', 'Hacking Watch', 'Live Feed'],
  },
  {
    id: 'yt-gJnS0iSmrIQ',
    callsign: 'OS-DRK-45',
    sector: 'SEC-05 (DARKNET NETWORK)',
    elevation: 'Isolated Server Vault',
    sensorType: 'Signal Intelligence Interceptor',
    title: 'Deep Web Surveillance: Global Anomaly Intelligence Radar',
    channelName: 'Zero Day Radar',
    city: 'Stockholm Vault',
    stateOrRegion: 'DarkNet Sector',
    country: 'Cyber Operations',
    countryCode: 'CY',
    continent: 'Cyber Ops',
    latitude: 59.3293,
    longitude: 18.0686,
    category: 'Cyber Security / DarkWeb',
    youtubeId: 'gJnS0iSmrIQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/gJnS0iSmrIQ?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 7900,
    status: 'Online 24/7',
    description: 'Continuous anomaly monitoring tracking global malware dissemination vectors, BGP hijack alerts, and high-entropy traffic bursts.',
    tags: ['ZeroDay', 'DeepWeb', 'SignalIntel', 'Network Anomalies', 'Cyber Radar'],
  },
  {
    id: 'yt-jV_58covjEE',
    callsign: 'OS-DRK-46',
    sector: 'SEC-05 (DARKNET NETWORK)',
    elevation: 'Underground Fiber Repeater',
    sensorType: 'Encrypted Stream Demuxer',
    title: 'Dark Web Live Stream: Network Traffic & Terminal Feed',
    channelName: 'Shadow Net Live',
    city: 'Frankfurt Core',
    stateOrRegion: 'DarkNet Sector',
    country: 'Cyber Operations',
    countryCode: 'CY',
    continent: 'Cyber Ops',
    latitude: 50.1109,
    longitude: 8.6821,
    category: 'Cyber Security / DarkWeb',
    youtubeId: 'jV_58covjEE',
    embedUrl: 'https://www.youtube-nocookie.com/embed/jV_58covjEE?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 6700,
    status: 'Online 24/7',
    description: 'Live command center broadcast displaying active terminal scripts, network vulnerability sweeps, and encrypted stream diagnostics.',
    tags: ['ShadowNet', 'Terminal Live', 'Dark Web', 'Network Stream', 'Cyber Defense'],
  },
  {
    id: 'yt-KPmA5GU_KZM',
    callsign: 'OS-DRK-47',
    sector: 'SEC-05 (DARKNET NETWORK)',
    elevation: 'Tactical Recon Station',
    sensorType: 'Heuristic Intrusion Sensor',
    title: 'DarkWeb Reconnaissance & Autonomous Sentinel Stream',
    channelName: 'Sentinel Guard',
    city: 'Zurich Secure SOC',
    stateOrRegion: 'DarkNet Sector',
    country: 'Cyber Operations',
    countryCode: 'CY',
    continent: 'Cyber Ops',
    latitude: 47.3769,
    longitude: 8.5417,
    category: 'Cyber Security / DarkWeb',
    youtubeId: 'KPmA5GU_KZM',
    embedUrl: 'https://www.youtube-nocookie.com/embed/KPmA5GU_KZM?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 8100,
    status: 'Online 24/7',
    description: 'Autonomous sentinel scanning honeypots, monitoring unauthorized port inquiries, and logging anomalous darknet signatures in real-time.',
    tags: ['Sentinel', 'Intrusion Detection', 'DarkWeb Recon', 'SOC Watch', 'Hacker Live'],
  },
  {
    id: 'yt-BnC6xVa_7W8',
    callsign: 'OS-TOR-48',
    sector: 'SEC-05 (TOR NETWORK)',
    elevation: 'Decentralized Relay',
    sensorType: 'Tor Circuit Analyzer',
    title: 'Live Tor Network & Onion Circuit Surveillance Video',
    channelName: 'Onion Watch Terminal',
    city: 'Helsinki Node',
    stateOrRegion: 'Tor Operations',
    country: 'Cyber Operations',
    countryCode: 'CY',
    continent: 'Cyber Ops',
    latitude: 60.1699,
    longitude: 24.9384,
    category: 'Cyber Security / DarkWeb',
    youtubeId: 'BnC6xVa_7W8',
    embedUrl: 'https://www.youtube-nocookie.com/embed/BnC6xVa_7W8?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 9200,
    status: 'Online 24/7',
    description: 'Live technical stream documenting Tor exit relay throughput, consensus status, encrypted routing paths, and privacy layer health.',
    tags: ['Tor Network', 'Onion Live', 'Privacy Relay', 'DarkNet Circuit', 'Encrypted'],
  },
  {
    id: 'yt-3vFIXQr9kfM',
    callsign: 'OS-CCTV-49',
    sector: 'SEC-05 (CCTV NETWORK)',
    elevation: 'Traffic Command Facility',
    sensorType: 'Closed-Circuit Multi-Camera Grid',
    title: 'Live CCTV Surveillance Camera Network Feed 2026',
    channelName: 'CCTV Global Watch',
    city: 'Global CCTV Center',
    stateOrRegion: 'Surveillance Grid',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 39.0458,
    longitude: -76.6413,
    category: 'Street & Traffic',
    youtubeId: '3vFIXQr9kfM',
    embedUrl: 'https://www.youtube-nocookie.com/embed/3vFIXQr9kfM?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 15800,
    status: 'Online 24/7',
    description: 'High-security multi-channel closed circuit television (CCTV) broadcast cycling between urban highways, logistics checkpoints, and transit stations.',
    tags: ['CCTV', 'Surveillance Feed', 'Camera Network', 'Traffic Grid', 'Live Watch'],
  },

  // --- HORROR / ABANDONED / PARANORMAL MYSTERY CAMERAS ---
  {
    id: 'yt-2nXAD-0KGZs',
    callsign: 'OS-HOR-50',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: 'Abandoned Compound',
    sensorType: 'Night Vision Full Spectrum IR',
    title: 'Live Horror & Paranormal Night Vision Investigation Cam',
    channelName: 'Paranormal Watch Live',
    city: 'Blackwood Forest',
    stateOrRegion: 'Pennsylvania',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 40.9699,
    longitude: -77.7278,
    category: 'Horror & Mystery',
    youtubeId: '2nXAD-0KGZs',
    embedUrl: 'https://www.youtube-nocookie.com/embed/2nXAD-0KGZs?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 10400,
    status: 'Online 24/7',
    description: '24/7 live night vision and thermal infrared surveillance observing abandoned estate grounds and anomalous shadows.',
    tags: ['Horror Live', 'Paranormal', 'Night Vision', 'Abandoned', 'Mystery Cam'],
  },
  {
    id: 'yt-k0Vxw1zd0xU',
    callsign: 'OS-HOR-51',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: 'Asylum Ruins',
    sensorType: 'Thermal Ghost Radar Optical Array',
    title: 'Live Horror 2026: Abandoned Asylum Paranormal Camera',
    channelName: 'Ghost Hunt 24/7',
    city: 'Waverly Environs',
    stateOrRegion: 'Kentucky',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 38.1367,
    longitude: -85.8361,
    category: 'Horror & Mystery',
    youtubeId: 'k0Vxw1zd0xU',
    embedUrl: 'https://www.youtube-nocookie.com/embed/k0Vxw1zd0xU?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 8800,
    status: 'Online 24/7',
    description: 'Continuous night surveillance inside historic abandoned asylum corridors equipped with motion alarms and audio frequency meters.',
    tags: ['Horror 2026', 'Asylum', 'Ghost Hunt', 'Paranormal Cam', 'Live Stream'],
  },
  {
    id: 'yt-NJMLYCKAewY',
    callsign: 'OS-HOR-52',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: 'Haunted Mansion',
    sensorType: 'Infrared Motion Matrix',
    title: 'Live Horror 2026: Haunted Manor Corridors & Basement',
    channelName: 'Midnight Paranormal',
    city: 'Savannah',
    stateOrRegion: 'Georgia',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 32.0809,
    longitude: -81.0912,
    category: 'Horror & Mystery',
    youtubeId: 'NJMLYCKAewY',
    embedUrl: 'https://www.youtube-nocookie.com/embed/NJMLYCKAewY?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 9700,
    status: 'Online 24/7',
    description: 'Live multi-room spooky camera setup streaming historic haunted manor hallways, basements, and old cemetery gates.',
    tags: ['Haunted Manor', 'Horror Cam', 'Savannah', 'Paranormal Live', 'Night Camera'],
  },
  {
    id: 'yt-uDPnIlw_CB4',
    callsign: 'OS-HOR-53',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: 'Deep Woodlands',
    sensorType: 'Forest Audio-Optical Tripwire',
    title: 'Live Horror Video Today: Deep Forest Cryptid & Shadow Cam',
    channelName: 'Shadow Woods Live',
    city: 'Pine Barrens',
    stateOrRegion: 'New Jersey',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 39.8168,
    longitude: -74.4578,
    category: 'Horror & Mystery',
    youtubeId: 'uDPnIlw_CB4',
    embedUrl: 'https://www.youtube-nocookie.com/embed/uDPnIlw_CB4?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 7600,
    status: 'Online 24/7',
    description: 'Surveillance stream stationed deep in the nocturnal forest monitoring unexplained woodland sounds, movement, and shadows.',
    tags: ['Horror Video', 'Forest Cam', 'Pine Barrens', 'Cryptid Watch', 'Night Live'],
  },
  {
    id: 'yt-ludAgiwR0wA',
    callsign: 'OS-HOR-54',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: 'Subterranean Bunker',
    sensorType: 'DarkWeb Mystery CCTV',
    title: 'Horror DarkWeb Live Video: Subterranean Ruins & Vaults',
    channelName: 'Underground Mystery',
    city: 'Catacombs Sector',
    stateOrRegion: 'Bunker Network',
    country: 'United Kingdom',
    countryCode: 'GB',
    continent: 'Europe',
    latitude: 51.5155,
    longitude: -0.1419,
    category: 'Horror & Mystery',
    youtubeId: 'ludAgiwR0wA',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ludAgiwR0wA?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/London (BST)',
    timezoneOffsetHours: 1,
    viewersCount: 11800,
    status: 'Online 24/7',
    description: 'Underground subterranean exploration feed live streaming dark corridors, abandoned bunkers, and mysterious chamber tunnels.',
    tags: ['Horror DarkWeb', 'Catacombs', 'Underground', 'Bunker Cam', 'Mystery Video'],
  },
  {
    id: 'yt-yLGPb3I3Ml8',
    callsign: 'OS-HOR-55',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: 'Old Industrial Facility',
    sensorType: 'Full-Spectrum Anomaly Tracker',
    title: 'Horror DarkWeb Investigation: Abandoned Factory Surveillance',
    channelName: 'Dark Abandoned Live',
    city: 'Detroit Industrial Ruins',
    stateOrRegion: 'Michigan',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 42.3314,
    longitude: -83.0458,
    category: 'Horror & Mystery',
    youtubeId: 'yLGPb3I3Ml8',
    embedUrl: 'https://www.youtube-nocookie.com/embed/yLGPb3I3Ml8?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 8300,
    status: 'Online 24/7',
    description: 'Investigation camera streaming abandoned industrial plants, boiler rooms, and decaying warehouse zones at night.',
    tags: ['Horror DarkWeb', 'Abandoned Factory', 'Detroit Ruins', 'Industrial Cam', 'Live Horror'],
  },

  // --- OTHER WORLD WEBCAMS (EUROPE & AFRICA & OCEANIA) ---
  {
    id: 'yt-a1mcaV3Sf9U',
    callsign: 'OS-VEN-08',
    sector: 'SEC-02 (EUROPE SOUTH)',
    elevation: '2m ASL',
    sensorType: 'Lagoon Rolling Optical Array',
    title: 'Venice: 24/7 Rolling Cam – Grand Canal & Historic Palazzos',
    channelName: 'I Love You Venice',
    city: 'Venice',
    stateOrRegion: 'Veneto',
    country: 'Italy',
    countryCode: 'IT',
    continent: 'Europe',
    latitude: 45.4381,
    longitude: 12.3359,
    category: 'Landmark',
    youtubeId: 'a1mcaV3Sf9U',
    embedUrl: 'https://www.youtube-nocookie.com/embed/a1mcaV3Sf9U?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/Rome (CEST)',
    timezoneOffsetHours: 2,
    viewersCount: 4600,
    status: 'Online 24/7',
    description: 'Continuous 24/7 dynamic rolling camera stream switching across authentic vantage points along Venice\'s Grand Canal, gondola stations, and Renaissance facades.',
    tags: ['Venice', 'Italy', 'Grand Canal', 'Veneto', 'Gondolas Live'],
  },
  {
    id: 'yt-i10aOLMK76k',
    callsign: 'OS-VEN-09',
    sector: 'SEC-02 (EUROPE SOUTH)',
    elevation: '3m ASL',
    sensorType: 'Waterway Panorama Matrix',
    title: 'Live Cam Around the World: Rolling Cam & Lounge Stream',
    channelName: 'I Love You Venice',
    city: 'Venice',
    stateOrRegion: 'Veneto',
    country: 'Italy',
    countryCode: 'IT',
    continent: 'Europe',
    latitude: 45.4408,
    longitude: 12.3155,
    category: 'Global Network',
    youtubeId: 'i10aOLMK76k',
    embedUrl: 'https://www.youtube-nocookie.com/embed/i10aOLMK76k?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/Rome (CEST)',
    timezoneOffsetHours: 2,
    viewersCount: 2900,
    status: 'Online 24/7',
    description: 'Scenic world webcam network stream alternating between scenic European waterways, Venetian bridges, and ambient travel horizons.',
    tags: ['World Cam', 'Venice', 'Italy', 'Chill Stream', 'Travel Live'],
  },
  {
    id: 'yt-CEj5ws5v10',
    callsign: 'OS-LHR-10',
    sector: 'SEC-02 (EUROPE WEST)',
    elevation: '25m ASL',
    sensorType: 'Runway ILS Tracking Optical',
    title: 'London Heathrow Airport (LHR) Live Runway & Flight Operations',
    channelName: 'Flight Focus 365',
    city: 'London',
    stateOrRegion: 'Greater London',
    country: 'United Kingdom',
    countryCode: 'GB',
    continent: 'Europe',
    latitude: 51.4700,
    longitude: -0.4543,
    category: 'Airport & Aviation',
    youtubeId: '-CEj5ws5v10',
    embedUrl: 'https://www.youtube-nocookie.com/embed/-CEj5ws5v10?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/London (BST)',
    timezoneOffsetHours: 1,
    viewersCount: 5400,
    status: 'Live Stream',
    description: 'Live broadcast from London Heathrow Airport (LHR) by Flight Focus 365, streaming commercial jet arrivals, departures, and ground traffic operations on runways 09L/27R.',
    tags: ['Heathrow', 'LHR', 'London', 'Aviation', 'Planespotting'],
  },
  {
    id: 'yt-Zl_gKWFrgpA',
    callsign: 'OS-LON-11',
    sector: 'SEC-02 (EUROPE WEST)',
    elevation: '35m ASL',
    sensorType: 'Global C2 Switching Array',
    title: 'Global Webcams 24/7: Icons of the World in Real Time',
    channelName: 'Window Seat',
    city: 'London Hub',
    stateOrRegion: 'England',
    country: 'United Kingdom',
    countryCode: 'GB',
    continent: 'Europe',
    latitude: 51.5074,
    longitude: -0.1278,
    category: 'Global Network',
    youtubeId: 'Zl_gKWFrgpA',
    embedUrl: 'https://www.youtube-nocookie.com/embed/Zl_gKWFrgpA?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/London (BST)',
    timezoneOffsetHours: 1,
    viewersCount: 3800,
    status: 'Online 24/7',
    description: 'Continuous 24/7 world stream broadcasting live camera switches across famous landmarks, world capitals, skyline overlooks, and coastal wonders.',
    tags: ['Window Seat', 'Global Webcams', 'World Icons', '24/7 Stream', 'Travel'],
  },
  {
    id: 'yt-3nyPER2kzqk',
    callsign: 'OS-DUB-12',
    sector: 'SEC-02 (EUROPE WEST)',
    elevation: '15m ASL',
    sensorType: 'Cobblestone Street Recon Node',
    title: 'EarthCam Live: Dublin, Ireland – Temple Bar & City Center',
    channelName: 'EarthCam',
    city: 'Dublin',
    stateOrRegion: 'Leinster',
    country: 'Ireland',
    countryCode: 'IE',
    continent: 'Europe',
    latitude: 53.3454,
    longitude: -6.2642,
    category: 'Landmark',
    youtubeId: '3nyPER2kzqk',
    embedUrl: 'https://www.youtube-nocookie.com/embed/3nyPER2kzqk?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/Dublin (IST)',
    timezoneOffsetHours: 1,
    viewersCount: 3400,
    status: 'Online 24/7',
    description: 'Official EarthCam live feed from Dublin, Ireland showing the bustling pedestrian cobblestone streets of the historic Temple Bar cultural quarter.',
    tags: ['EarthCam', 'Dublin', 'Ireland', 'Temple Bar', 'City Center'],
  },
  {
    id: 'yt-HfgIFGbdGJ0',
    callsign: 'OS-MUC-13',
    sector: 'SEC-02 (EUROPE CENTRAL)',
    elevation: '519m ASL',
    sensorType: 'EarthTV Master C2 Matrix',
    title: 'The World Live – Original earthTV® Global Broadcast',
    channelName: 'earthTV',
    city: 'Munich',
    stateOrRegion: 'Bavaria',
    country: 'Germany',
    countryCode: 'DE',
    continent: 'Europe',
    latitude: 48.1351,
    longitude: 11.5820,
    category: 'Global Network',
    youtubeId: 'HfgIFGbdGJ0',
    embedUrl: 'https://www.youtube-nocookie.com/embed/HfgIFGbdGJ0?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/Berlin (CEST)',
    timezoneOffsetHours: 2,
    viewersCount: 6200,
    status: 'Online 24/7',
    description: 'The world-famous earthTV live network stream cycling through hundreds of high-definition cameras in top metropolises, natural marvels, and historic monuments globally.',
    tags: ['earthTV', 'Global Webcams', 'Munich', 'World Travel', '24/7 Live'],
  },
  {
    id: 'yt-Li3Dvqlo5uE',
    callsign: 'OS-ALP-14',
    sector: 'SEC-02 (EUROPE CENTRAL)',
    elevation: '1,780m ASL',
    sensorType: 'Alpine Meteorological Panorama Array',
    title: 'Destination Deutschland: 24/7 Live Stream Webcams Germany',
    channelName: 'feratel – your window to the world',
    city: 'Bavarian Alps / Munich',
    stateOrRegion: 'Bavaria',
    country: 'Germany',
    countryCode: 'DE',
    continent: 'Europe',
    latitude: 47.4921,
    longitude: 11.0958,
    category: 'Nature & Alps',
    youtubeId: 'Li3Dvqlo5uE',
    embedUrl: 'https://www.youtube-nocookie.com/embed/Li3Dvqlo5uE?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/Berlin (CEST)',
    timezoneOffsetHours: 2,
    viewersCount: 2600,
    status: 'Online 24/7',
    description: 'Official feratel panorama webcam network showcasing German mountain peaks, Bavarian valleys, lakes, castles, and historic city squares 24/7.',
    tags: ['feratel', 'Germany', 'Bavarian Alps', 'Munich', 'Panorama'],
  },
  {
    id: '_0wPODlF9wU',
    callsign: 'OS-ROC-15',
    sector: 'SEC-01 (NORTH AMERICA NORTH)',
    elevation: '1,409m ASL',
    sensorType: 'Alpine Sub-Zero Sensor Array',
    title: 'Canmore Main Street & Canadian Rockies Livecam',
    channelName: 'CanmoreAlberta.com',
    city: 'Canmore',
    stateOrRegion: 'Alberta',
    country: 'Canada',
    countryCode: 'CA',
    continent: 'North America',
    latitude: 51.0890,
    longitude: -115.3590,
    category: 'Nature & Alps',
    youtubeId: '_0wPODlF9wU',
    embedUrl: 'https://www.youtube-nocookie.com/embed/_0wPODlF9wU?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Edmonton (MDT)',
    timezoneOffsetHours: -6,
    viewersCount: 2100,
    status: 'Online 24/7',
    description: 'Live HD camera situated on Main Street in the alpine town of Canmore in the Canadian Rocky Mountains, offering majestic views of the Three Sisters and mountain weather.',
    tags: ['Canmore', 'Alberta', 'Canadian Rockies', 'Canada Live', 'Alpine Town'],
  },
  {
    id: 'yt-ydYDqZQpim8',
    callsign: 'OS-NAM-16',
    sector: 'SEC-03 (AFRICA SOUTH)',
    elevation: '890m ASL',
    sensorType: 'Solar-Powered Night IR Wildlife Array',
    title: 'Namibia: Live Stream in the Namib Desert (Gondwana Waterhole)',
    channelName: 'NamibiaCam',
    city: 'Namib Desert Lodge',
    stateOrRegion: 'Hardap',
    country: 'Namibia',
    countryCode: 'NA',
    continent: 'Africa',
    latitude: -24.1167,
    longitude: 15.8667,
    category: 'Wildlife Safari',
    youtubeId: 'ydYDqZQpim8',
    embedUrl: 'https://www.youtube-nocookie.com/embed/ydYDqZQpim8?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Africa/Windhoek (CAT)',
    timezoneOffsetHours: 2,
    viewersCount: 16400,
    status: 'Online 24/7',
    description: 'Famous 24/7 solar-powered live camera at the Gondwana Namib Park waterhole in Namibia. Watch wild oryx (gemsbok), springbok, zebras, giraffes, jackals, and desert storms.',
    tags: ['NamibiaCam', 'Namib Desert', 'Wildlife', 'Waterhole', 'Africa Live'],
  },
  {
    id: 'yt-XsOU8JnEpNM',
    callsign: 'OS-KEN-17',
    sector: 'SEC-03 (AFRICA EAST)',
    elevation: '1,120m ASL',
    sensorType: 'Savannah Thermal IR Sensor',
    title: 'ol Donyo Lodge: Wildlife Live Stream – Kenya Safari',
    channelName: 'Africam',
    city: 'Chyulu Hills',
    stateOrRegion: 'Makueni',
    country: 'Kenya',
    countryCode: 'KE',
    continent: 'Africa',
    latitude: -2.4833,
    longitude: 37.8167,
    category: 'Wildlife Safari',
    youtubeId: 'XsOU8JnEpNM',
    embedUrl: 'https://www.youtube-nocookie.com/embed/XsOU8JnEpNM?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Africa/Nairobi (EAT)',
    timezoneOffsetHours: 3,
    viewersCount: 4700,
    status: 'Online 24/7',
    description: 'Africam wildlife stream from ol Donyo Lodge nestled in the Chyulu Hills of south-eastern Kenya, facing Mount Kilimanjaro and visited by elephant herds and big cats.',
    tags: ['Africam', 'Kenya', 'Safari', 'Elephants', 'Chyulu Hills'],
  },
  {
    id: 'yt-FyFAqPHBKiQ',
    callsign: 'OS-SAMUI-07',
    sector: 'SEC-04 (SOUTHEAST ASIA)',
    elevation: '4m ASL',
    sensorType: 'Gulf Maritime 4K Optical',
    title: 'Koh Samui – Fisherman\'s Village & Bophut Beach 4K Stream',
    channelName: 'The Real Samui Webcam',
    city: 'Koh Samui',
    stateOrRegion: 'Surat Thani',
    country: 'Thailand',
    countryCode: 'TH',
    continent: 'Asia',
    latitude: 9.5593,
    longitude: 100.0315,
    category: 'Beach & Ocean',
    youtubeId: 'FyFAqPHBKiQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/FyFAqPHBKiQ?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '4K Ultra HD',
    fps: 60,
    timezone: 'Asia/Bangkok (ICT)',
    timezoneOffsetHours: 7,
    viewersCount: 3100,
    status: 'Online 24/7',
    description: 'Live 2160p 4K stream from El Gaucho overlooking the crystal clear Gulf of Thailand, beachfront restaurants, and traditional longtail boats in Fisherman\'s Village, Bophut.',
    tags: ['Koh Samui', 'Thailand', 'Bophut Beach', 'Gulf of Thailand', '4K Beach'],
  },
  {
    id: 'yt-5uZa3-RMFos',
    callsign: 'OS-SYD-18',
    sector: 'SEC-04 (OCEANIA PACIFIC)',
    elevation: '32m ASL',
    sensorType: 'Maritime 4K Harbour PTZ',
    title: 'WebcamSydney 1: Sydney Harbour & Opera House Live 24/7',
    channelName: 'WebcamSydney',
    city: 'Sydney',
    stateOrRegion: 'New South Wales',
    country: 'Australia',
    countryCode: 'AU',
    continent: 'Oceania',
    latitude: -33.8568,
    longitude: 151.2153,
    category: 'Landmark',
    youtubeId: '5uZa3-RMFos',
    embedUrl: 'https://www.youtube-nocookie.com/embed/5uZa3-RMFos?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '4K Ultra HD',
    fps: 60,
    timezone: 'Australia/Sydney (AEST)',
    timezoneOffsetHours: 10,
    viewersCount: 6900,
    status: 'Online 24/7',
    description: 'Direct high-resolution live stream from WebcamSydney capturing the iconic Sydney Harbour, Sydney Opera House sails, Harbour Bridge, and cruise ship terminals.',
    tags: ['WebcamSydney', 'Sydney Opera House', 'Sydney Harbour', 'Australia', '4K Live'],
  },

  // --- NEW VERIFIED FEEDS BATCH 2026 ---
  {
    id: 'yt-B4-L2nfGcuE',
    callsign: 'OS-ISS-56',
    sector: 'SEC-00 (LOW EARTH ORBIT)',
    elevation: '408km LEO',
    sensorType: 'Orbital Ultra-HD Earth Cam Array',
    title: 'NASA ISS Live: Real-Time Earth Orbit Video Stream 24/7',
    channelName: 'Space Live HD',
    city: 'ISS Orbit',
    stateOrRegion: 'Orbital Path',
    country: 'International Space Station',
    countryCode: 'US',
    continent: 'Space',
    latitude: 28.5729,
    longitude: -80.6490,
    category: 'Space Orbit',
    youtubeId: 'B4-L2nfGcuE',
    embedUrl: 'https://www.youtube-nocookie.com/embed/B4-L2nfGcuE?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'UTC (Zulu Time)',
    timezoneOffsetHours: 0,
    viewersCount: 22400,
    status: 'Online 24/7',
    description: 'Live continuous HD broadcast from cameras mounted outside the International Space Station (ISS), showing breathtaking views of Earth rotating from low Earth orbit.',
    tags: ['NASA', 'ISS', 'Space Orbit', 'Earth from Space', 'Live Stream'],
  },
  {
    id: 'yt--rP06IdNgMI',
    callsign: 'OS-LAS-57',
    sector: 'SEC-01 (NORTH AMERICA WEST)',
    elevation: '610m ASL',
    sensorType: 'Panoramic Strip Array PTZ',
    title: 'EarthCam Live: Las Vegas Strip & Bellagio Fountains 24/7',
    channelName: 'EarthCam',
    city: 'Las Vegas',
    stateOrRegion: 'Nevada',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 36.1126,
    longitude: -115.1767,
    category: 'Landmark',
    youtubeId: '-rP06IdNgMI',
    embedUrl: 'https://www.youtube-nocookie.com/embed/-rP06IdNgMI?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Los_Angeles (PDT)',
    timezoneOffsetHours: -7,
    viewersCount: 13800,
    status: 'Online 24/7',
    description: 'Live 24/7 surveillance capturing the world-famous Las Vegas Boulevard, Bellagio Fountain spectacles, and neon illuminated casino resorts.',
    tags: ['Las Vegas', 'Bellagio', 'Nevada', 'EarthCam', 'Casino Strip'],
  },
  {
    id: 'yt-7xdHH9KMSVk',
    callsign: 'OS-TOK-58',
    sector: 'SEC-04 (EAST ASIA)',
    elevation: '95m ASL',
    sensorType: 'Ultra HD Metropole PTZ',
    title: 'Tokyo Live Cam: Shinjuku & Shibuya Crossing Metropolis 24/7',
    channelName: 'Tokyo Live Cam',
    city: 'Tokyo',
    stateOrRegion: 'Kanto',
    country: 'Japan',
    countryCode: 'JP',
    continent: 'Asia',
    latitude: 35.6938,
    longitude: 139.7034,
    category: 'Street & Traffic',
    youtubeId: '7xdHH9KMSVk',
    embedUrl: 'https://www.youtube-nocookie.com/embed/7xdHH9KMSVk?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Asia/Tokyo (JST)',
    timezoneOffsetHours: 9,
    viewersCount: 16700,
    status: 'Online 24/7',
    description: 'Live camera streaming the pulsing high-tech center of Shinjuku and Shibuya, bullet trains, and neon skyline in Tokyo, Japan.',
    tags: ['Tokyo', 'Shinjuku', 'Japan', 'Street Life', 'Metropolis'],
  },
  {
    id: 'yt-Ja-aqt-rNjQ',
    callsign: 'OS-GLO-59',
    sector: 'SEC-01 (NORTH AMERICA EAST)',
    elevation: '50m ASL',
    sensorType: 'Multi-Channel C2 Satellite Array',
    title: 'World Live Webcams 24/7: Global Cityscapes & Sky Cams Feed',
    channelName: 'Global Network Cam',
    city: 'New York Hub',
    stateOrRegion: 'New York',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 40.7128,
    longitude: -74.0060,
    category: 'Global Network',
    youtubeId: 'Ja-aqt-rNjQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/Ja-aqt-rNjQ?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 8900,
    status: 'Online 24/7',
    description: 'Continuous real-time multi-angle global camera broadcast streaming international skylines, harbor docks, and iconic world overlooks.',
    tags: ['Global Cam', 'World Network', 'Cityscapes', 'Skyline', 'Live 24/7'],
  },
  {
    id: 'yt-oAPTCI0aNR0',
    callsign: 'OS-HOR-60',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: '24m ASL',
    sensorType: 'Full-Spectrum Infrared Shadow Sensor',
    title: 'Live Horror Investigation: Spooky Haunted Manor Night Vision Cam',
    channelName: 'Nightmare Investigations Live',
    city: 'Salem Environs',
    stateOrRegion: 'Massachusetts',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 42.5195,
    longitude: -70.8967,
    category: 'Horror & Mystery',
    youtubeId: 'oAPTCI0aNR0',
    embedUrl: 'https://www.youtube-nocookie.com/embed/oAPTCI0aNR0?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 11400,
    status: 'Online 24/7',
    description: '24/7 live night vision and paranormal monitoring inside historic colonial manor hallways, attics, and eerie surrounding grounds.',
    tags: ['Horror Live', 'Paranormal', 'Night Vision', 'Haunted Manor', 'Ghost Cam'],
  },
  {
    id: 'yt-YhF_S6L7Cp8',
    callsign: 'OS-HOR-61',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: '110m ASL',
    sensorType: 'Low-Light Thermal EMF Sensor',
    title: 'Live Horror & Mystery 2026: Abandoned Hospital Ward Investigation',
    channelName: 'Ghost Hunting Live',
    city: 'Old Trent Ruins',
    stateOrRegion: 'Staffordshire',
    country: 'United Kingdom',
    countryCode: 'GB',
    continent: 'Europe',
    latitude: 53.0027,
    longitude: -2.1794,
    category: 'Horror & Mystery',
    youtubeId: 'YhF_S6L7Cp8',
    embedUrl: 'https://www.youtube-nocookie.com/embed/YhF_S6L7Cp8?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/London (BST)',
    timezoneOffsetHours: 1,
    viewersCount: 9300,
    status: 'Online 24/7',
    description: 'Live surveillance stream covering abandoned hospital corridors, operating rooms, and anomalous night activity with live audio meters.',
    tags: ['Live Horror', 'Abandoned Hospital', 'Ghost Hunting', 'UK Ruins', 'Mystery Live'],
  },
  {
    id: 'yt-J8jLVawzH2I',
    callsign: 'OS-HOR-62',
    sector: 'SEC-06 (PARANORMAL & MYSTERY)',
    elevation: '2m ASL',
    sensorType: 'Passive Acoustic & Infrared Array',
    title: 'Live Horror 2026: Nocturnal Crypt & Graveyard Mystery Cam',
    channelName: 'Cryptid & Ghost Live',
    city: 'New Orleans',
    stateOrRegion: 'Louisiana',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 29.9511,
    longitude: -90.0715,
    category: 'Horror & Mystery',
    youtubeId: 'J8jLVawzH2I',
    embedUrl: 'https://www.youtube-nocookie.com/embed/J8jLVawzH2I?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Chicago (CDT)',
    timezoneOffsetHours: -5,
    viewersCount: 10800,
    status: 'Online 24/7',
    description: 'Continuous nocturnal stream station monitoring historic above-ground cemetery vaults, Spanish moss oaks, and mysterious shadow movement.',
    tags: ['Horror Live', 'New Orleans', 'Cemetery', 'Night Camera', 'Paranormal'],
  },
  {
    id: 'yt-vByZX49lCic',
    callsign: 'OS-MED-63',
    sector: 'SEC-02 (EUROPE SOUTH)',
    elevation: '120m ASL',
    sensorType: 'Cycladic Cliff Coastal Array',
    title: 'Live World Camera: Mediterranean Coast & Port Panorama 24/7',
    channelName: 'Aegean Live Views',
    city: 'Santorini',
    stateOrRegion: 'South Aegean',
    country: 'Greece',
    countryCode: 'GR',
    continent: 'Europe',
    latitude: 36.3932,
    longitude: 25.4615,
    category: 'Beach & Ocean',
    youtubeId: 'vByZX49lCic',
    embedUrl: 'https://www.youtube-nocookie.com/embed/vByZX49lCic?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/Athens (EEST)',
    timezoneOffsetHours: 3,
    viewersCount: 6400,
    status: 'Online 24/7',
    description: 'Live 24/7 panoramic broadcast streaming whitewashed cliffside villas, Aegean turquoise seas, volcanic calderas, and Mediterranean luxury yachts.',
    tags: ['Santorini', 'Greece', 'Aegean Sea', 'Mediterranean', 'Coastline'],
  },
  {
    id: 'yt-oI8R4_UG3Fs',
    callsign: 'OS-FOR-64',
    sector: 'SEC-02 (NORTHERN NATURE)',
    elevation: '190m ASL',
    sensorType: 'Bio-Acoustic Wilderness Lens',
    title: 'Live Forest & Wildlife Webcam: Deep Pine Wilderness Stream 24/7',
    channelName: 'Nordic Forest Live',
    city: 'Taiga National Park',
    stateOrRegion: 'Lapland',
    country: 'Finland',
    countryCode: 'FI',
    continent: 'Europe',
    latitude: 66.5039,
    longitude: 25.7294,
    category: 'Nature & Alps',
    youtubeId: 'oI8R4_UG3Fs',
    embedUrl: 'https://www.youtube-nocookie.com/embed/oI8R4_UG3Fs?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Europe/Helsinki (EEST)',
    timezoneOffsetHours: 3,
    viewersCount: 5200,
    status: 'Online 24/7',
    description: 'Direct high-definition forest feed capturing ancient pine woods, wildlife foraging, gentle wind, rustling streams, and serene nature sounds.',
    tags: ['Forest Cam', 'Wilderness', 'Lapland', 'Nature Live', 'Finland'],
  },
  {
    id: 'yt-RZFMYVNhd4k',
    callsign: 'OS-NAM-65',
    sector: 'SEC-03 (AFRICA SOUTH)',
    elevation: '780m ASL',
    sensorType: 'Solar-Powered Thermal IR Safari Cam',
    title: 'Namib Desert Live Cam: African Wildlife Waterhole Stream 24/7',
    channelName: 'NamibiaCam',
    city: 'Namib-Naukluft',
    stateOrRegion: 'Gondwana Namib Park',
    country: 'Namibia',
    countryCode: 'NA',
    continent: 'Africa',
    latitude: -24.4983,
    longitude: 15.9328,
    category: 'Wildlife Safari',
    youtubeId: 'RZFMYVNhd4k',
    embedUrl: 'https://www.youtube-nocookie.com/embed/RZFMYVNhd4k?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'Africa/Windhoek (CAT)',
    timezoneOffsetHours: 2,
    viewersCount: 14700,
    status: 'Online 24/7',
    description: 'Official 24/7 live stream from the remote Namib Desert waterhole where oryx, zebras, giraffes, jackals, and desert elephants gather under vast African skies.',
    tags: ['NamibiaCam', 'Namib Desert', 'Wildlife', 'Waterhole', 'Africa Live'],
  },
  {
    id: 'yt-iSeH45R-8R0',
    callsign: 'OS-SVO-66',
    sector: 'SEC-01 (NORTH AMERICA WEST)',
    elevation: '32m ASL',
    sensorType: 'Smart AI Optical Sensor Node',
    title: 'Google Live: Silicon Valley & Global Tech Hub 4K Surveillance',
    channelName: 'Tech Matrix Live',
    city: 'Mountain View',
    stateOrRegion: 'California',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 37.4220,
    longitude: -122.0841,
    category: 'Landmark',
    youtubeId: 'iSeH45R-8R0',
    embedUrl: 'https://www.youtube-nocookie.com/embed/iSeH45R-8R0?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '4K Ultra HD',
    fps: 60,
    timezone: 'America/Los_Angeles (PDT)',
    timezoneOffsetHours: -7,
    viewersCount: 7800,
    status: 'Online 24/7',
    description: 'Live camera feed streaming Silicon Valley tech corridors, innovation centers, and autonomous vehicle street traffic in California.',
    tags: ['Google', 'Silicon Valley', 'Mountain View', 'California', 'Tech Hub'],
  },
  {
    id: 'yt-mexGMd6-8ik',
    callsign: 'OS-GEO-67',
    sector: 'SEC-00 (GLOBAL ORBIT & CITIES)',
    elevation: '450km LEO',
    sensorType: 'Orbital 3D Photogrammetry Array',
    title: 'Google Earth Live Stream: Global Metropolis 4K Cityscapes',
    channelName: 'Google Earth Matrix',
    city: 'World Capitals Matrix',
    stateOrRegion: 'Global Satellite Grid',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 40.7128,
    longitude: -74.0060,
    category: 'Global Network',
    youtubeId: 'mexGMd6-8ik',
    embedUrl: 'https://www.youtube-nocookie.com/embed/mexGMd6-8ik?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '4K Ultra HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 12100,
    status: 'Online 24/7',
    description: 'Continuous 4K stream exploring Earth\'s most breathtaking megalopolises, terrain wonders, architectural feats, and global skylines.',
    tags: ['Google Earth', 'Global Webcams', '4K Metropolis', 'Cityscapes', 'Earth 3D'],
  },
  {
    id: 'yt-zMCea32gpmg',
    callsign: 'OS-URB-68',
    sector: 'SEC-01 (NORTH AMERICA CENTRAL)',
    elevation: '185m ASL',
    sensorType: 'High-Density Urban Surveillance Lens',
    title: 'Google Live Webcams: High-Definition World Urban Center Views',
    channelName: 'Google Urban Watch',
    city: 'Chicago',
    stateOrRegion: 'Illinois',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 41.8818,
    longitude: -87.6231,
    category: 'Street & Traffic',
    youtubeId: 'zMCea32gpmg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/zMCea32gpmg?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/Chicago (CDT)',
    timezoneOffsetHours: -5,
    viewersCount: 8400,
    status: 'Online 24/7',
    description: 'Real-time street and architectural surveillance tracking urban transportation pulses, highway arteries, and skyscraper panoramas.',
    tags: ['Google Live', 'Urban Center', 'Traffic Grid', 'Chicago', 'World Cams'],
  },
  {
    id: 'yt-6M6rK0ssjYg',
    callsign: 'OS-TRN-69',
    sector: 'SEC-01 (NORTH AMERICA CENTRAL)',
    elevation: '238m ASL',
    sensorType: 'Railway Telemetry PTZ Tracker',
    title: 'Live RailCam: High-Speed Train & Railway Junction 24/7 Stream',
    channelName: 'RailStream Live',
    city: 'Fostoria Iron Triangle',
    stateOrRegion: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    continent: 'North America',
    latitude: 41.1578,
    longitude: -83.4169,
    category: 'Street & Traffic',
    youtubeId: '6M6rK0ssjYg',
    embedUrl: 'https://www.youtube-nocookie.com/embed/6M6rK0ssjYg?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: '1080p Full HD',
    fps: 60,
    timezone: 'America/New_York (EDT)',
    timezoneOffsetHours: -4,
    viewersCount: 9600,
    status: 'Online 24/7',
    description: '24/7 live high-definition railway camera capturing heavy freight trains, locomotives, switching operations, and rail junctions in real-time.',
    tags: ['RailCam', 'Trains Live', 'RailStream', 'Locomotive', 'Iron Triangle'],
  },
  {
    id: 'yt-2xSX9JErzqM',
    callsign: 'OS-DEV-70',
    sector: 'SEC-05 (DEVELOPMENT FEEDS)',
    elevation: '0m ASL',
    sensorType: 'External YouTube Live Feed',
    title: 'Development Live Webcam Feed 01',
    channelName: 'YouTube Live',
    city: 'Unverified Source',
    stateOrRegion: 'External Feed',
    country: 'Cyber & DarkNet',
    countryCode: 'CY',
    continent: 'Development Network',
    latitude: 52.0,
    longitude: 10.0,
    category: 'Development Feed',
    youtubeId: '2xSX9JErzqM',
    embedUrl: 'https://www.youtube-nocookie.com/embed/2xSX9JErzqM?autoplay=1&mute=1&playsinline=1&rel=0',
    resolution: 'YouTube Live',
    fps: 30,
    timezone: 'UTC',
    timezoneOffsetHours: 0,
    viewersCount: 0,
    status: 'External Feed',
    description: 'User-provided external YouTube live feed for development and testing purposes.',
    tags: ['Development', 'External Feed', 'YouTube Live'],
  },
  {
    id: 'yt-4lHAyiUuckY', callsign: 'OS-DEV-71', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 02', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 49.0, longitude: 8.0, category: 'Development Feed', youtubeId: '4lHAyiUuckY', embedUrl: 'https://www.youtube-nocookie.com/embed/4lHAyiUuckY?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-bd4lqAWNPJw', callsign: 'OS-DEV-72', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 03', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 55.0, longitude: 15.0, category: 'Development Feed', youtubeId: 'bd4lqAWNPJw', embedUrl: 'https://www.youtube-nocookie.com/embed/bd4lqAWNPJw?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-EhDz-Ge_ufM', callsign: 'OS-DEV-73', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 04', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 47.0, longitude: 20.0, category: 'Development Feed', youtubeId: 'EhDz-Ge_ufM', embedUrl: 'https://www.youtube-nocookie.com/embed/EhDz-Ge_ufM?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-Y4eIXH7O1z8', callsign: 'OS-DEV-74', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 05', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 43.0, longitude: 25.0, category: 'Development Feed', youtubeId: 'Y4eIXH7O1z8', embedUrl: 'https://www.youtube-nocookie.com/embed/Y4eIXH7O1z8?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-OkQ0utdxwBY', callsign: 'OS-DEV-75', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 06', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 39.0, longitude: 30.0, category: 'Development Feed', youtubeId: 'OkQ0utdxwBY', embedUrl: 'https://www.youtube-nocookie.com/embed/OkQ0utdxwBY?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-77akujLn4k8', callsign: 'OS-DEV-76', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 07', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 35.0, longitude: 35.0, category: 'Development Feed', youtubeId: '77akujLn4k8', embedUrl: 'https://www.youtube-nocookie.com/embed/77akujLn4k8?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-GeB8rnbUISY', callsign: 'OS-DEV-77', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 08', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 31.0, longitude: 40.0, category: 'Development Feed', youtubeId: 'GeB8rnbUISY', embedUrl: 'https://www.youtube-nocookie.com/embed/GeB8rnbUISY?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-WKGK_hYnlGE', callsign: 'OS-DEV-78', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 09', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 27.0, longitude: 45.0, category: 'Development Feed', youtubeId: 'WKGK_hYnlGE', embedUrl: 'https://www.youtube-nocookie.com/embed/WKGK_hYnlGE?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-fO9e9jnhYK8', callsign: 'OS-DEV-79', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 10', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 23.0, longitude: 50.0, category: 'Development Feed', youtubeId: 'fO9e9jnhYK8', embedUrl: 'https://www.youtube-nocookie.com/embed/fO9e9jnhYK8?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt--29gQhlOsTQ', callsign: 'OS-DEV-80', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 11', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 19.0, longitude: 55.0, category: 'Development Feed', youtubeId: '-29gQhlOsTQ', embedUrl: 'https://www.youtube-nocookie.com/embed/-29gQhlOsTQ?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-DwKCna1mumk', callsign: 'OS-DEV-81', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 12', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 15.0, longitude: 60.0, category: 'Development Feed', youtubeId: 'DwKCna1mumk', embedUrl: 'https://www.youtube-nocookie.com/embed/DwKCna1mumk?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-6DS40wWyKzA', callsign: 'OS-DEV-82', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 13', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 11.0, longitude: 65.0, category: 'Development Feed', youtubeId: '6DS40wWyKzA', embedUrl: 'https://www.youtube-nocookie.com/embed/6DS40wWyKzA?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-2r0iuqfUW7E', callsign: 'OS-DEV-83', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 14', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 7.0, longitude: 70.0, category: 'Development Feed', youtubeId: '2r0iuqfUW7E', embedUrl: 'https://www.youtube-nocookie.com/embed/2r0iuqfUW7E?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
  {
    id: 'yt-a1mcaV3Sf9U', callsign: 'OS-DEV-84', sector: 'SEC-05 (DEVELOPMENT FEEDS)', elevation: '0m ASL', sensorType: 'External YouTube Live Feed', title: 'Development Live Webcam Feed 15', channelName: 'YouTube Live', city: 'Unverified Source', stateOrRegion: 'External Feed', country: 'Cyber & DarkNet', countryCode: 'CY', continent: 'Development Network', latitude: 3.0, longitude: 75.0, category: 'Development Feed', youtubeId: 'a1mcaV3Sf9U', embedUrl: 'https://www.youtube-nocookie.com/embed/a1mcaV3Sf9U?autoplay=1&mute=1&playsinline=1&rel=0', resolution: 'YouTube Live', fps: 30, timezone: 'UTC', timezoneOffsetHours: 0, viewersCount: 0, status: 'External Feed', description: 'User-provided external YouTube live feed for development and testing purposes.', tags: ['Development', 'External Feed', 'YouTube Live']
  },
];

export interface CountryGroup {
  name: string;
  code: string;
  flag: string;
  lat: number;
  lng: number;
  zoom: number;
  count: number;
  sectorCallsign: string;
}

// Dynamically compute country counts and sectors based on USER_LIVE_WEBCAMS
export const COUNTRY_GROUPS: CountryGroup[] = [
  {
    name: 'India',
    code: 'IN',
    flag: '🇮🇳',
    lat: 22.5,
    lng: 78.5,
    zoom: 5,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'IN').length,
    sectorCallsign: 'SEC-04 (IN)',
  },
  {
    name: 'Cyber & DarkNet',
    code: 'CY',
    flag: '🛡️',
    lat: 52.0,
    lng: 10.0,
    zoom: 4,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'CY').length,
    sectorCallsign: 'SEC-05 (CY)',
  },
  {
    name: 'United States',
    code: 'US',
    flag: '🇺🇸',
    lat: 38.0,
    lng: -97.0,
    zoom: 4,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'US').length,
    sectorCallsign: 'SEC-01 (US)',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    flag: '🇬🇧',
    lat: 53.0,
    lng: -1.5,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'GB').length,
    sectorCallsign: 'SEC-02 (GB)',
  },
  {
    name: 'Japan',
    code: 'JP',
    flag: '🇯🇵',
    lat: 36.2048,
    lng: 138.2529,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'JP').length,
    sectorCallsign: 'SEC-04 (JP)',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    flag: '🇦🇪',
    lat: 24.5,
    lng: 54.5,
    zoom: 7,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'AE').length,
    sectorCallsign: 'SEC-04 (AE)',
  },
  {
    name: 'France',
    code: 'FR',
    flag: '🇫🇷',
    lat: 46.603354,
    lng: 1.888334,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'FR').length,
    sectorCallsign: 'SEC-02 (FR)',
  },
  {
    name: 'Germany',
    code: 'DE',
    flag: '🇩🇪',
    lat: 51.1657,
    lng: 10.4515,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'DE').length,
    sectorCallsign: 'SEC-02 (DE)',
  },
  {
    name: 'Italy',
    code: 'IT',
    flag: '🇮🇹',
    lat: 42.5,
    lng: 12.5,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'IT').length,
    sectorCallsign: 'SEC-02 (IT)',
  },
  {
    name: 'Australia',
    code: 'AU',
    flag: '🇦🇺',
    lat: -25.2744,
    lng: 133.7751,
    zoom: 4,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'AU').length,
    sectorCallsign: 'SEC-04 (AU)',
  },
  {
    name: 'Greece',
    code: 'GR',
    flag: '🇬🇷',
    lat: 39.0742,
    lng: 21.8243,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'GR').length,
    sectorCallsign: 'SEC-02 (GR)',
  },
  {
    name: 'Finland',
    code: 'FI',
    flag: '🇫🇮',
    lat: 61.9241,
    lng: 25.7482,
    zoom: 5,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'FI').length,
    sectorCallsign: 'SEC-02 (FI)',
  },
  {
    name: 'Thailand',
    code: 'TH',
    flag: '🇹🇭',
    lat: 13.5,
    lng: 100.9925,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'TH').length,
    sectorCallsign: 'SEC-04 (TH)',
  },
  {
    name: 'Canada',
    code: 'CA',
    flag: '🇨🇦',
    lat: 56.1304,
    lng: -106.3468,
    zoom: 4,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'CA').length,
    sectorCallsign: 'SEC-01 (CA)',
  },
  {
    name: 'Namibia (Africa)',
    code: 'NA',
    flag: '🇳🇦',
    lat: -22.5609,
    lng: 17.0658,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'NA').length,
    sectorCallsign: 'SEC-03 (NA)',
  },
  {
    name: 'Kenya (Africa)',
    code: 'KE',
    flag: '🇰🇪',
    lat: -1.2921,
    lng: 36.8219,
    zoom: 6,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'KE').length,
    sectorCallsign: 'SEC-03 (KE)',
  },
  {
    name: 'Ireland',
    code: 'IE',
    flag: '🇮🇪',
    lat: 53.4129,
    lng: -8.2439,
    zoom: 7,
    count: USER_LIVE_WEBCAMS.filter((c) => c.countryCode === 'IE').length,
    sectorCallsign: 'SEC-02 (IE)',
  },
];
