create table if not exists public.securewatch_tenants (
  session_id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.ip_chat_messages (
  id bigint generated by default as identity primary key,
  room text not null,
  sender_ip text not null,
  sender_id text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create index if not exists ip_chat_messages_room_id_idx
  on public.ip_chat_messages (room, id);